---
- name: Copy mysql_maintain to place
  copy: src=mysqlcheck_cron dest=/usr/local/sbin/mysqlcheck_cron owner=root group=root mode=0755

- name: Remove old cron
  file:
    name: /etc/cron.d/mysqlcheck
    state: absent
